#ifndef SIMBOLOS_NO_TERMINALES_H
#define SIMBOLOS_NO_TERMINALES_H

#define SIMBOLOS_NO_TERMINALES_PROGRAMA_VALOR "programa"
#define SIMBOLOS_NO_TERMINALES_INSTRUCCIONES_VALOR "instrucciones"
#define SIMBOLOS_NO_TERMINALES_SENTENCIA_VALOR "sentencia"
#define SIMBOLOS_NO_TERMINALES_FUNCION_VALOR "funcion"
#define SIMBOLOS_NO_TERMINALES_FUNCION_NUMERICA_VALOR "funcion_numerica"
#define SIMBOLOS_NO_TERMINALES_FUNCION_BOOLEANA_VALOR "funcion_booleana"
#define SIMBOLOS_NO_TERMINALES_IS_ZERO_VALOR "isZero"
#define SIMBOLOS_NO_TERMINALES_TRIANGLE_AREA_MAXIMUM_VALOR "triangleAreaMaximum"
#define SIMBOLOS_NO_TERMINALES_TRIANGULO_VALOR "triangulo"
#define SIMBOLOS_NO_TERMINALES_COORDENADA_VALOR "coordenada"
#define SIMBOLOS_NO_TERMINALES_DECLARACION_VALOR "declaracion"
#define SIMBOLOS_NO_TERMINALES_LISTA_DECLARACIONES_VALOR "lista_declaraciones"
#define SIMBOLOS_NO_TERMINALES_DECLARACION_VAR_VALOR "declaracion_var"
#define SIMBOLOS_NO_TERMINALES_LISTA_IDS_VALOR "lista_ids"
#define SIMBOLOS_NO_TERMINALES_TIPO_VALOR "tipo"
#define SIMBOLOS_NO_TERMINALES_ASIGNACION_VALOR "asignacion"
#define SIMBOLOS_NO_TERMINALES_WRITE_VALOR "write"
#define SIMBOLOS_NO_TERMINALES_READ_VALOR "read"
#define SIMBOLOS_NO_TERMINALES_CICLO_VALOR "ciclo"
#define SIMBOLOS_NO_TERMINALES_IF_VALOR "if"
#define SIMBOLOS_NO_TERMINALES_BLOQUE_IF_VALOR "bloque_if"
#define SIMBOLOS_NO_TERMINALES_ELSE_VALOR "else"
#define SIMBOLOS_NO_TERMINALES_CONDICIONAL_VALOR "condicional"
#define SIMBOLOS_NO_TERMINALES_CONDICION_COMPUESTA_VALOR "condicion_compuesta"
#define SIMBOLOS_NO_TERMINALES_CONDICION_UNARIA_VALOR "condicion_unaria"
#define SIMBOLOS_NO_TERMINALES_PREDICADO_VALOR "predicado"
#define SIMBOLOS_NO_TERMINALES_OPERADOR_COMPARACION_VALOR "operador_comparacion"
#define SIMBOLOS_NO_TERMINALES_EXPRESION_VALOR "expresion"
#define SIMBOLOS_NO_TERMINALES_TERMINO_VALOR "termino"
#define SIMBOLOS_NO_TERMINALES_FACTOR_VALOR "factor"

#define SIMBOLOS_NO_TERMINALES_CANT 30
typedef enum
{
    SIMBOLOS_NO_TERMINALES_PROGRAMA,
    SIMBOLOS_NO_TERMINALES_INSTRUCCIONES,
    SIMBOLOS_NO_TERMINALES_SENTENCIA,
    SIMBOLOS_NO_TERMINALES_FUNCION,
    SIMBOLOS_NO_TERMINALES_FUNCION_NUMERICA,
    SIMBOLOS_NO_TERMINALES_FUNCION_BOOLEANA,
    SIMBOLOS_NO_TERMINALES_IS_ZERO,
    SIMBOLOS_NO_TERMINALES_TRIANGLE_AREA_MAXIMUM,
    SIMBOLOS_NO_TERMINALES_TRIANGULO,
    SIMBOLOS_NO_TERMINALES_COORDENADA,
    SIMBOLOS_NO_TERMINALES_DECLARACION,
    SIMBOLOS_NO_TERMINALES_LISTA_DECLARACIONES,
    SIMBOLOS_NO_TERMINALES_DECLARACION_VAR,
    SIMBOLOS_NO_TERMINALES_LISTA_IDS,
    SIMBOLOS_NO_TERMINALES_TIPO,
    SIMBOLOS_NO_TERMINALES_ASIGNACION,
    SIMBOLOS_NO_TERMINALES_WRITE,
    SIMBOLOS_NO_TERMINALES_READ,
    SIMBOLOS_NO_TERMINALES_CICLO,
    SIMBOLOS_NO_TERMINALES_IF,
    SIMBOLOS_NO_TERMINALES_BLOQUE_IF,
    SIMBOLOS_NO_TERMINALES_ELSE,
    SIMBOLOS_NO_TERMINALES_CONDICIONAL,
    SIMBOLOS_NO_TERMINALES_CONDICION_COMPUESTA,
    SIMBOLOS_NO_TERMINALES_CONDICION_UNARIA,
    SIMBOLOS_NO_TERMINALES_PREDICADO,
    SIMBOLOS_NO_TERMINALES_OPERADOR_COMPARACION,
    SIMBOLOS_NO_TERMINALES_EXPRESION,
    SIMBOLOS_NO_TERMINALES_TERMINO,
    SIMBOLOS_NO_TERMINALES_FACTOR
} t_simbolos_no_terminales;

const char *simbolos_no_terminales_obtener_valor(t_simbolos_no_terminales no_terminal);
t_simbolos_no_terminales simbolos_no_terminales_obtener_desde_string(const char *str);

#endif // SIMBOLOS_NO_TERMINALES_H