#ifndef PUNTEROS_ARBOL_SINTACTICO_H
#define PUNTEROS_ARBOL_SINTACTICO_H

#include "../arbol_sintactico.h"

extern t_arbol_sintactico_nodo *punteros_arbol_sintactico_programa;
extern t_arbol_sintactico_nodo *punteros_arbol_sintactico_instrucciones;
extern t_arbol_sintactico_nodo *punteros_arbol_sintactico_sentencia;
extern t_arbol_sintactico_nodo *punteros_arbol_sintactico_funcion;
extern t_arbol_sintactico_nodo *punteros_arbol_sintactico_funcion_numerica;
extern t_arbol_sintactico_nodo *punteros_arbol_sintactico_funcion_booleana;
extern t_arbol_sintactico_nodo *punteros_arbol_sintactico_isZero;
extern t_arbol_sintactico_nodo *punteros_arbol_sintactico_triangleAreaMaximum;
extern t_arbol_sintactico_nodo *punteros_arbol_sintactico_triangulo;
extern t_arbol_sintactico_nodo *punteros_arbol_sintactico_coordenada;
extern t_arbol_sintactico_nodo *punteros_arbol_sintactico_declaracion;
extern t_arbol_sintactico_nodo *punteros_arbol_sintactico_lista_declaraciones;
extern t_arbol_sintactico_nodo *punteros_arbol_sintactico_declaracion_var;
extern t_arbol_sintactico_nodo *punteros_arbol_sintactico_lista_ids;
extern t_arbol_sintactico_nodo *punteros_arbol_sintactico_tipo;
extern t_arbol_sintactico_nodo *punteros_arbol_sintactico_asignacion;
extern t_arbol_sintactico_nodo *punteros_arbol_sintactico_write;
extern t_arbol_sintactico_nodo *punteros_arbol_sintactico_read;
extern t_arbol_sintactico_nodo *punteros_arbol_sintactico_ciclo;
extern t_arbol_sintactico_nodo *punteros_arbol_sintactico_if;
extern t_arbol_sintactico_nodo *punteros_arbol_sintactico_bloque_if;
extern t_arbol_sintactico_nodo *punteros_arbol_sintactico_else;
extern t_arbol_sintactico_nodo *punteros_arbol_sintactico_condicional;
extern t_arbol_sintactico_nodo *punteros_arbol_sintactico_condicion_compuesta;
extern t_arbol_sintactico_nodo *punteros_arbol_sintactico_condicion_unaria;
extern t_arbol_sintactico_nodo *punteros_arbol_sintactico_predicado;
extern t_arbol_sintactico_nodo *punteros_arbol_sintactico_operador_comparacion;
extern t_arbol_sintactico_nodo *punteros_arbol_sintactico_expresion;
extern t_arbol_sintactico_nodo *punteros_arbol_sintactico_termino;
extern t_arbol_sintactico_nodo *punteros_arbol_sintactico_factor;

#endif